### ISSUE TITLE
No support for InMemoryUploadedFile

### ISSUE THREAD

**Issue by bendavis78** [SmileyChris/easy-thumbnails#143]
I'm writing an app in which I need to be able to thumbnail an InMemoryUploadedFile, however, easy_thumbnails does not seem to support the processing of StringIO objects, as they do not have an "open()" method.  I would like to keep the thumbnail in memory, because it is eventually going into a Cairo document, and I don't need it in the file system.  Currently, I don't see any way to thumbnail a file which is in memory.  I think it would be somewhat beneficial to have some method of processing thumbnails in memory, without having to store in the filesystem.

**Comment by GasparPizarro** [comment]
Pretty sure it's related to #417, but still has a weird behavior. If I have a random model with a `FileField` with no intention of getting a thumbnail from (say a video or pdf file), when I save it the `saved_file`signal is sent, and it fails with 

    AttributeError: '_io.BufferedReader' object has no attribute '_committed'

Is that expected behavior? What if I have a `FileField` with a text file inside? Do I need to do something to make `easy_thumbnails` ignore that type of files?
