### ISSUE TITLE
"Suspension not allowed here" error

### ISSUE THREAD

**Issue by epicserve** [SmileyChris/easy-thumbnails#223]
In my Celery log files I was getting the error, "Suspension not allowed here", from PIL when running my generate_thumbnails task. I added the following to my Django settings file which seems to have fixed the issue.

I'm adding this as an issue so that others might come across the fix or so something can be added into easy-thumbnails so people don't get the error.

``` python
# The following fixes the PIL "Suspension not allowed here" error
#1048576 Bytes = 1 MB
from PIL import ImageFile
ImageFile.MAXBLOCK = 1048576
```

**Comment by danielquinn** [comment]
I'm using Pillow and this is still happening to me:

```python
from easy_thumbnails.templatetags.thumbnail import thumbnail_url
image = Image.objects.get(slug='my-slug')
thumbnail_url(image.file_shopped, "my_arbitrary_alias")
# Suspension not allowed here
# Suspension not allowed here
# Out[3]: ''
```
The funny thing is that this doesn't happen on my development machine (Gentoo), but it *does* happen in production (CentOS6).

Pillow is up to date:

```bash
$ pip freeze | grep P
Pillow==2.7.0
```

So now I'm out of ideas.  I've basically resorted to pre-generating all thumbnails on the development server and rsyncing to production, which is obviously not awesome :-(

**Comment by epicserve** [comment]
Did you make sure you uninstalled PIL?

**Comment by danielquinn** [comment]
I'm running in a virtualenv that I created with `--no-site-packages` and when I run `pip freeze` I get:

```
Django==1.7.5
Markdown==2.6
MySQL-python==1.2.3
Pillow==2.7.0
argparse==1.3.0
arrow==0.5.4
cssmin==0.2.0
dateutils==0.6.6
django-autocomplete-light==2.0.7
django-crocodile==0.4.1
django-debug-toolbar==1.2.2
django-extensions==1.5.0
django-model-utils==1.3.1
django-secure==1.0.1
django-treebeard==3.0
docutils==0.7
easy-thumbnails==2.2
egenix-mx-base==3.1.3
ipython==0.13.2
numpy==1.5.0
oauthlib==0.7.2
psycopg2==2.5.4
pycrypto==2.3
python-dateutil==2.4.0
pytz==2014.10
reportlab==2.4
requests==2.4.3
requests-oauthlib==0.4.1
six==1.9.0
sqlparse==0.1.14
tweepy==2.1
ujson==1.33
virtualenv==1.11.3
virtualenvwrapper==3.4
wsgiref==0.1.2
```

Now here's the thing, *some* of that stuff wasn't installed by me.  Specifically MySQL:

```bash
$ pip uninstall MySQL-python
Not uninstalling MySQL-python at /usr/local/lib/python2.7/site-packages, outside environment /home/my_user/.virtualenvs/my_virtualenv
```

So are you suggesting that even though PIL doesn't show up in `pip freeze`, it's somehow interfereing in my virtualenv?  Is there a way to make it stop that?  The virtualenv was created with:

    virtualenv --python=$(which python2.7) --no-site-packages ~/.virtualenvs/my_virtualenv

**Comment by epicserve** [comment]
Having both PIL and Pillow installed has been known to create conflicts, iirc.

Having ``MySQL-python`` in your list is weird. I'm assuming you didn't accidentally run ``pip freeze`` and forget to activate your virtualenv. That's about the only reason I can think it would list ``MySQL-python``, if you didn't install it. Unless, you forgot you installed it or another package had it as one of it's requirements.

The easiest thing to do if you are seeing weirdness in your virtualenv, is to nuke it and create a new one. FYI, according to my version of virtualenv (1.11.6) ``--no-site-packages`` is DEPRECATED. From the help, "Retained only for backward compatibility. Not having access to global site-packages is now the default behavior."

**Comment by SmileyChris** [comment]
I'd suggest nuking from orbit and starting again.

Destroy the virtualenv, ensure you have the latest version of virtualenv
installed, recreate it and install your requirements.

**Comment by danielquinn** [comment]
It turns out that the problem was that somehow packages from outside my virtualenv were seeping in, and the the fix (according to my hosting provider, Webfaction) was to put a file called `sitecustomize` in `~/.virtualenvs/my_virtualenv/lib/python2.7/`.

Thanks for the troubleshooting, maybe if someone searches for this problem in the future, my experiences will help.

**Comment by SmileyChris** [comment]
Thanks for the followup, Daniel!

**Comment by Apreche** [comment]
I'm handling a large database of images, and just one of them has caused this error to appear. I researched it and found this Github issue and some other threads all claiming that this has been fixed in Pillow, but not in PIL. I have never installed PIL, and only used Pillow. I tested and the problem existed in Pillow versions 2.7.0, 2.8.0, and 2.8.1. I did not try older Pillow versions.

People seem to suggest the problem occurs when the jpg is too big. The file that caused this error is actually very small. It's 656KB 127 x 275.

Through some research I discovered the problem appeared because the JPG had 32-bit color depth. I didn't even know that JPG could have 32-bit color. Pretty sure this is just a bad file, so it should be OK for it to fail. 

Even so, Pillow handles this bad file perfectly well, as long as optimize=False. If you have the combination of the 32 bit jpeg and optimize=True, then the error appears. I also tried opening the image in Windows paint and re-saving it as a proper 24-bit jpg. That new jpg worked just fine. All other applications seem to handle this strange jpg without error. Though most of them render the colors incorrectly, probably because it doesn't contain a  proper icc profile.

What was really an even bigger problem is that this error didn't raise a Python Exception. it just prints out "Suspension not allowed here" and continues on its merry way. If it would raise an exception, I could at least catch it and retry the save call with optimize=False.
