### ISSUE TITLE
ForeignKey on_delete deprecation warning

### ISSUE THREAD

**Issue by satyagrahaa** [SmileyChris/easy-thumbnails#449]
Hi there,
My tests fail due to this issue:

File "/root/venv/3.4/lib/python3.4/site-packages/easy_thumbnails/migrations/0001_initial.py", line 34, in Migration
    ('source', models.ForeignKey(related_name='thumbnails', to='easy_thumbnails.Source')),
  File "/root/venv/3.4/lib/python3.4/site-packages/django/db/models/fields/related.py", line 773, in __init__
    RemovedInDjango20Warning, 2)
django.utils.deprecation.RemovedInDjango20Warning: on_delete will be a required arg for ForeignKey in Django 2.0. Set it to models.CASCADE on models and in existing migrations if you want to maintain the current default behavior. See https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.ForeignKey.on_delete

Any suggestions?

**Comment by claudep** [comment]
This is fixed in master by 15d51862a40dde2ccd4ab64c.

**Comment by saeed-eskano** [comment]
True that you have fixed it by  [15d5186](https://github.com/SmileyChris/easy-thumbnails/commit/15d51862a40dde2ccd4ab64c370d291c6a85990d), however it is not included `easy-thumbnails` latest release (version 2.3) on pypi.

When I install from master branch rather than pypi using ``-e git+git@github.com:SmileyChris/easy-thumbnails.git@master#egg=easy-thumbnails`` It is fine, but the warning still exists if I install the package from pypi.

**Comment by claudep** [comment]
See #452.

**Comment by SmileyChris** [comment]
Released
