### ISSUE TITLE
Saving TIFF image raises Value error

### ISSUE THREAD

**Issue by jrief** [SmileyChris/easy-thumbnails#610]
On attempt to save an image of type `TIFF` PIL raises a ValueError complaining with: "quality setting only supported for 'jpeg' compression".

This can easily be prevented removing the `quality` key from the options dictionary.

I already prepared a patch for this issue.

**Comment by jrief** [comment]
unfortunately I introduced a regression in version 2.8.4. I tried to revert this, but now running
the unit tests fails. This presumably is because GitHub changed something in their action
scripts. Please check the "Install dependencies" section in those two jobs
https://github.com/SmileyChris/easy-thumbnails/actions/runs/3696468077/jobs/6260204110
https://github.com/SmileyChris/easy-thumbnails/actions/runs/3866392805/jobs/6590486709

Therefore I'd like to propose to replace tox by GitHub's own matrix runner. In all of my projects
I do it that way, and in my opinion that's a better approach. What do you think?

**Comment by mireq** [comment]
Problem is in setup.py on this line:
https://github.com/SmileyChris/easy-thumbnails/blob/c75a28152044f4f9cf3245d0acaa58a2c76ad4a3/setup.py#L25

Previous version imported get_version from
https://github.com/SmileyChris/easy-thumbnails/blob/c75a28152044f4f9cf3245d0acaa58a2c76ad4a3/easy_thumbnails/__init__.py#L4

But now is imported file `easy_thumbnails/get_version.py` as module instead of function. Either `get_version` function should be renamed to something unique like `get_package_version` or module get_version should be renamed to prevent name conflict.
