### ISSUE TITLE
DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by anderspetersson** [SmileyChris/easy-thumbnails#631]
easy-thumbnails==2.8.5
python3.11

easy_thumbnails/optimize/post_processor.py:3:

DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
  from imghdr import what as determinetype

Here is how https://github.com/streamlit/streamlit migrated from imghdr to using Pillow functionality: https://github.com/streamlit/streamlit/commit/3d5dd61aef2bf649c5bfe42aad53cf1426beb094

**Comment by benkonrath** [comment]
The file is already open in the streamit example which is why they just use PIL. For easy-thumbnails, I think we'll need to use one of the suggested replacements found in the deprecation table, or 'vendor' the imghdr module into the code base (licenses have to allow this of course). 

https://peps.python.org/pep-0594/#deprecated-modules

If we use one of the suggested libraries, care needs to be taken to ensure it produces the same result. e.g. 'jpeg' for Jpegs and not 'jpg', 'JPEG', 'JPG', etc.

**Comment by anderspetersson** [comment]
Python 3.13 is out and this issue are preventing me from upgrading. Is it time to migrate to another package or can we get a decision how to move forward with fixing this issue?

**Comment by benkonrath** [comment]
It turns out PIL can be used here (see PR). That made the update easier.
